#### What is Numpy ?

Numpy is the fundamental package for scientific computing in Python.It is a python library that provides a multidimensional array object.
At the core of numpy package ,is the ndarray object.This encapsulates n-dimensional arrays of homogeneous data types

#### Creating Numpy arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#np.random
np.random.random((3,4))

array([[0.94341197, 0.27480016, 0.66673777, 0.11599329],
       [0.05825281, 0.02612443, 0.92966565, 0.02149565],
       [0.77373558, 0.19358322, 0.83743981, 0.66708687]])

In [10]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [11]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Array attributes

In [15]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
#ndim
a3.ndim

3

In [18]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
#itemsize
a3.itemsize

8

In [20]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


#### Changing Datatype

In [21]:
# as type
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#### Array Operations

In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Scalar operations

In [23]:
#arithmatic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [24]:
# relational
a2 == 15


array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
#vector operations
#arithmatic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

#### Array functions

In [26]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 58., 100.,  22.],
       [ 97.,  50.,  97.],
       [ 96.,  84.,  48.]])

In [27]:
#max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([540096., 420000., 102432.])

In [28]:
#mean,median,std,var
np.var(a1,axis=1)

array([1016.        ,  490.88888889,  416.        ])

In [29]:
#trignometric functions
np.sin(a1)

array([[ 0.99287265, -0.50636564, -0.00885131],
       [ 0.37960774, -0.26237485,  0.37960774],
       [ 0.98358775,  0.73319032, -0.76825466]])

In [30]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [31]:
# log and exponents
np.exp(a1)

array([[1.54553894e+25, 2.68811714e+43, 3.58491285e+09],
       [1.33833472e+42, 5.18470553e+21, 1.33833472e+42],
       [4.92345829e+41, 3.02507732e+36, 7.01673591e+20]])

In [32]:
#round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[80., 16., 36.],
       [57., 81., 95.]])

#### Indexing and slicing

In [33]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a3[1,1,0]

6

In [38]:
a3[1,0,1]

5

In [39]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1[2:5:2]

array([2, 4])

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [43]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [44]:
a2[1,::3]

array([4, 7])

In [45]:
a2[0,:]

array([0, 1, 2, 3])

In [46]:
a2[:,2]

array([ 2,  6, 10])

In [47]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [49]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [51]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [52]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [53]:
a3[0,1,:]

array([3, 4, 5])

#### Iterating

In [54]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [55]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [57]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [59]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#### Reshaping

In [60]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [61]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [62]:
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### Stacking

In [63]:
#horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [65]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### splitting


In [66]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [68]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division