#### np.sort

Returns a sorted copy of an array

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[16, 99, 61, 55],
       [51, 45, 30, 99],
       [30,  1, 96, 66],
       [ 6,  1, 99, 61],
       [55, 49, 51, 86],
       [49, 77, 12, 61]])

In [6]:
np.sort(a)

array([ 5, 11, 35, 39, 42, 53, 58, 60, 72, 74, 78, 81, 88, 93, 96])

In [10]:
np.sort(b,axis=0)

array([[ 6,  1, 12, 55],
       [16,  1, 30, 61],
       [30, 45, 51, 61],
       [49, 49, 61, 66],
       [51, 77, 96, 86],
       [55, 99, 99, 99]])

#### np.append

The numpy append appends values along the mentioned axis at the end of the array

In [11]:
#code
np.append(a,200)

array([  5,  88,  11,  81,  72,  53,  60,  74,  35,  39,  96,  93,  42,
        58,  78, 200])

In [12]:
b

array([[16, 99, 61, 55],
       [51, 45, 30, 99],
       [30,  1, 96, 66],
       [ 6,  1, 99, 61],
       [55, 49, 51, 86],
       [49, 77, 12, 61]])

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[16.        , 99.        , 61.        , 55.        ,  0.24598574],
       [51.        , 45.        , 30.        , 99.        ,  0.28443074],
       [30.        ,  1.        , 96.        , 66.        ,  0.88287798],
       [ 6.        ,  1.        , 99.        , 61.        ,  0.38657985],
       [55.        , 49.        , 51.        , 86.        ,  0.17727552],
       [49.        , 77.        , 12.        , 61.        ,  0.93349799]])

#### np.concatenate

numpy concatenate() function concatenates a squence of arrays along an existing axis

In [15]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)

print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### np.unique

With the help of np.unique() method we can get the unique values from an array given as parameter in np.unique() method

In [19]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [20]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#### np.expand_dims

With the help of Numpy.expand_dims method,we can get the expanded dimensions of an array

In [22]:
a.shape

(15,)

In [23]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [24]:
np.expand_dims(a,axis=1).shape

(15, 1)

#### np.where

The numpy().where function returns the indices of elements in an input array where the given condition is satisfied

In [25]:
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [26]:
np.where(a>50)

(array([ 1,  3,  4,  5,  6,  7, 10, 11, 13, 14]),)

In [28]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 5,  0, 11,  0,  0,  0,  0,  0, 35, 39,  0,  0, 42,  0,  0])

In [29]:
np.where(a%2 == 0,0,a)

array([ 5,  0, 11, 81,  0, 53,  0,  0, 35, 39,  0, 93,  0,  0,  0])

#### np.argmax

The numpy.argmax function returns the indices of the max element of the array in a particular axis

In [30]:
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [31]:
np.argmax(a)

10

In [32]:
b

array([[16, 99, 61, 55],
       [51, 45, 30, 99],
       [30,  1, 96, 66],
       [ 6,  1, 99, 61],
       [55, 49, 51, 86],
       [49, 77, 12, 61]])

In [35]:
np.argmax(b,axis=1)

array([1, 3, 2, 2, 3, 1])

In [36]:
np.argmin(a)

0

#### no.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis

In [37]:
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [38]:
np.cumsum(a)

array([  5,  93, 104, 185, 257, 310, 370, 444, 479, 518, 614, 707, 749,
       807, 885])

In [39]:
b

array([[16, 99, 61, 55],
       [51, 45, 30, 99],
       [30,  1, 96, 66],
       [ 6,  1, 99, 61],
       [55, 49, 51, 86],
       [49, 77, 12, 61]])

In [40]:
np.cumsum(b,axis=1)

array([[ 16, 115, 176, 231],
       [ 51,  96, 126, 225],
       [ 30,  31, 127, 193],
       [  6,   7, 106, 167],
       [ 55, 104, 155, 241],
       [ 49, 126, 138, 199]])

In [41]:
np.cumsum(b)

array([  16,  115,  176,  231,  282,  327,  357,  456,  486,  487,  583,
        649,  655,  656,  755,  816,  871,  920,  971, 1057, 1106, 1183,
       1195, 1256])

In [42]:
np.cumprod(a)

array([                   5,                  440,                 4840,
                     392040,             28226880,           1496024640,
                89761478400,        6642349401600,      232482229056000,
           9066806933184000,   870413465585664000,  7161476004628545536,
        5634087015046086656, -5264346454098903040, -4790653798104301568])

In [43]:
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [44]:
np.percentile(a,50)

60.0

In [45]:
np.median(a)

60.0

#### np.histogram

Numpy has a builtin numpy histogram function which represents the frequency of data distribution in the graphical form

In [46]:
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [47]:
np.histogram(a,bins=[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

#### np.corrcoef

Returns the pearson product moment correlation coefficients

In [48]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

#### np.isin

With the help of numpy.isin() method ,we can see that one array having values are checked in a different numpy array having different elements with different sizes

In [49]:
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [50]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60])

#### np.flip

The numpy.flip() function reverses the order of the array of elements along the specified axis,preserving the shape of the array

In [51]:
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [52]:
np.flip(a)

array([78, 58, 42, 93, 96, 39, 35, 74, 60, 53, 72, 81, 11, 88,  5])

In [53]:
b

array([[16, 99, 61, 55],
       [51, 45, 30, 99],
       [30,  1, 96, 66],
       [ 6,  1, 99, 61],
       [55, 49, 51, 86],
       [49, 77, 12, 61]])

In [54]:
np.flip(b,axis=1)

array([[55, 61, 99, 16],
       [99, 30, 45, 51],
       [66, 96,  1, 30],
       [61, 99,  1,  6],
       [86, 51, 49, 55],
       [61, 12, 77, 49]])

#### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array.Array indexed works on flattened array

In [55]:
a

array([ 5, 88, 11, 81, 72, 53, 60, 74, 35, 39, 96, 93, 42, 58, 78])

In [56]:
np.put(a,[0,1],[110,530])

In [57]:
a

array([110, 530,  11,  81,  72,  53,  60,  74,  35,  39,  96,  93,  42,
        58,  78])

#### np.delete

The numpy.delete() function returns a new array with a deletion of sub arrays aong with the mentioned axis

In [58]:
a

array([110, 530,  11,  81,  72,  53,  60,  74,  35,  39,  96,  93,  42,
        58,  78])

In [60]:
np.delete(a,[0,2,4])

array([530,  81,  53,  60,  74,  35,  39,  96,  93,  42,  58,  78])

#### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [61]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
np.setdiff1d(n,m)

array([6, 7])

In [64]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [65]:
m[np.in1d(m,1)]

array([1])

#### np.clip

numpy().clip function is used to clip(limit) the values in an array

In [66]:
a

array([110, 530,  11,  81,  72,  53,  60,  74,  35,  39,  96,  93,  42,
        58,  78])

In [67]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 75, 72, 53, 60, 74, 35, 39, 75, 75, 42, 58, 75])