#### Numpy vs Python lists

In [1]:
#speed

#list

a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

0.792090892791748


In [2]:
#numpy
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time() - start)

0.051834821701049805


In [3]:
0.79/0.05

15.8

In [4]:
#memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [6]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

#### Advanced indexing

In [7]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a[1,2]

6

In [9]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [10]:
#fancy indexing

a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [11]:
#boolean indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[71, 39, 73, 57],
       [36, 25, 12, 32],
       [71, 24, 38, 92],
       [72,  4, 36, 59],
       [27,  1, 75, 69],
       [ 4, 95, 48, 27]])

In [13]:
#find all numbers greater than 50
a[a > 50]

array([71, 73, 57, 71, 92, 72, 59, 75, 69, 95])

In [14]:
#find out even numbers
a[a%2 == 0]

array([36, 12, 32, 24, 38, 92, 72,  4, 36,  4, 48])

In [16]:
#find all numbers greater than 50 and are even
a[(a>50) & (a%2 == 0)]

array([92, 72])

In [17]:
#find all numbers not divisble by 7
a[~(a%7 == 0)]

array([71, 39, 73, 57, 36, 25, 12, 32, 71, 24, 38, 92, 72,  4, 36, 59, 27,
        1, 75, 69,  4, 95, 48, 27])